[project]
name = "telemetry-sender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "protobuf>=6.31.1",
    "pyserial>=3.5",
]
